[2022-12-04 05:12:09,815] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.json_to_csv manual__2022-12-04T05:10:32.775557+00:00 [queued]>
[2022-12-04 05:12:09,849] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.json_to_csv manual__2022-12-04T05:10:32.775557+00:00 [queued]>
[2022-12-04 05:12:09,849] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 05:12:09,849] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 05:12:09,849] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 05:12:09,893] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): json_to_csv> on 2022-12-04 05:10:32.775557+00:00
[2022-12-04 05:12:09,902] {standard_task_runner.py:52} INFO - Started process 1952 to run task
[2022-12-04 05:12:09,913] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'json_to_csv', 'manual__2022-12-04T05:10:32.775557+00:00', '--job-id', '205', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpdzs7anuk', '--error-file', '/tmp/tmpx0m4gamc']
[2022-12-04 05:12:09,918] {standard_task_runner.py:77} INFO - Job 205: Subtask json_to_csv
[2022-12-04 05:12:10,043] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.json_to_csv manual__2022-12-04T05:10:32.775557+00:00 [running]> on host f96e892f1d4c
[2022-12-04 05:12:10,180] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=json_to_csv
AIRFLOW_CTX_EXECUTION_DATE=2022-12-04T05:10:32.775557+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-04T05:10:32.775557+00:00
[2022-12-04 05:12:10,181] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 33, in save_as_csv
    data_json = json.load(file)
  File "/usr/local/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2022-12-04 05:12:10,215] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=json_to_csv, execution_date=20221204T051032, start_date=20221204T051209, end_date=20221204T051210
[2022-12-04 05:12:10,269] {standard_task_runner.py:92} ERROR - Failed to execute job 205 for task json_to_csv
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 33, in save_as_csv
    data_json = json.load(file)
  File "/usr/local/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2022-12-04 05:12:10,329] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-12-04 05:12:10,449] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
